vrrp_script check_haproxy {
    script "killall -0 haproxy"
    interval 2
    weight 2
}

vrrp_instance VI_K8S_HA {
    state MASTER
    interface eth0
    virtual_router_id 100
    priority 255
    advert_int 1
    authentication { 
        auth_type PASS; 
        auth_pass k8s_ha_pwd; 
    }
    virtual_ipaddress {
        192.168.1.100/24
        192.168.1.200/24
    }
    track_script { check_haproxy }
}