vrrp_instance VI_K8S_WORKER {
    state MASTER          # เครื่องที่ 2, 3 ให้ใส่ BACKUP
    interface eth0
    virtual_router_id 61  # ห้ามซ้ำกับ ID ของ Master
    priority 255          # เครื่องที่ 2 ใส่ 250, เครื่องที่ 3 ใส่ 245
    advert_int 1
    authentication { auth_type PASS; auth_pass k8s_web_pwd; }
    virtual_ipaddress { 192.168.1.200 }
}